/*
 * generated by Xtext
 */
package politicianBiDsl.validation

import org.eclipse.xtext.validation.Check
import politicianBiDsl.pBiDsl.City
import politicianBiDsl.pBiDsl.PBiDslPackage
import politicianBiDsl.pBiDsl.Party
import politicianBiDsl.pBiDsl.Politician

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class PBiDslValidator extends AbstractPBiDslValidator {

  public static val INVALID_ENTITY_NAME = 'politicianBiDsl.pBiDsl.InvalidCityName'
  
  public static val INVALID_PRESIDENT = 'politicianBiDsl.pBiDsl.InvalidPresident'
  

	@Check
	def checkGreetingStartsWithCapital(City city) {
		if (!Character.isUpperCase(city.name.charAt(0))) {
			warning('Name should start with a capital', 
					PBiDslPackage::eINSTANCE.city_Name,
					INVALID_ENTITY_NAME,
					city.name)
		}
	}
	
	@Check
	def PresidentIsAPolitician(Party party) {
		if (party.president.getClass().isInstance(Politician))
		{
			warning('President should be a Politician', 
					PBiDslPackage::eINSTANCE.politician_Name,
					INVALID_PRESIDENT,
					party.president.name)
		}
	}
	
}
