/*
* generated by Xtext
*/
package politicianBiDsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PBiDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return politicianBiDsl.ui.internal.PBiDslActivator.getInstance().getInjector("politicianBiDsl.PBiDsl");
	}
	
}
