/*
 * generated by Xtext
 */
package politicianBiDsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import politicianBiDsl.ui.internal.PBiDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PBiDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PBiDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PBiDslActivator.getInstance().getInjector(PBiDslActivator.POLITICIANBIDSL_PBIDSL);
	}
	
}
