/**
 * generated by Xtext
 */
package politicianBiDsl.ui.quickfix;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.diagnostics.Diagnostic;
import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.model.edit.ISemanticModification;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import politicianBiDsl.PBiDslModelUtil;
import politicianBiDsl.pBiDsl.City;
import politicianBiDsl.validation.PBiDslValidator;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class PBiDslQuickfixProvider extends DefaultQuickfixProvider {
  @Fix(PBiDslValidator.INVALID_ENTITY_NAME)
  public void capitalizeCityNameFirstLetter(final Issue issue, final IssueResolutionAcceptor acceptor) {
    String[] _data = issue.getData();
    String _get = _data[0];
    String _plus = ("Capitalize first letter of \'" + _get);
    String _plus_1 = (_plus + "\'");
    final IModification _function = new IModification() {
      public void apply(final IModificationContext context) throws Exception {
        final IXtextDocument xtextDocument = context.getXtextDocument();
        Integer _offset = issue.getOffset();
        final String firstLetter = xtextDocument.get((_offset).intValue(), 1);
        Integer _offset_1 = issue.getOffset();
        String _firstUpper = StringExtensions.toFirstUpper(firstLetter);
        xtextDocument.replace((_offset_1).intValue(), 1, _firstUpper);
      }
    };
    acceptor.accept(issue, 
      "Capitalize first letter", _plus_1, 
      "City.gif", _function);
  }
  
  @Fix(Diagnostic.LINKING_DIAGNOSTIC)
  public void createMissingCityName(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final ISemanticModification _function = new ISemanticModification() {
      public void apply(final EObject element, final IModificationContext context) throws Exception {
        City _containerOfType = EcoreUtil2.<City>getContainerOfType(element, City.class);
        IXtextDocument _xtextDocument = context.getXtextDocument();
        Integer _offset = issue.getOffset();
        Integer _length = issue.getLength();
        String _get = _xtextDocument.get((_offset).intValue(), (_length).intValue());
        PBiDslModelUtil.addPartyOnACity(_containerOfType, _get);
      }
    };
    acceptor.accept(issue, 
      "Create missing name", 
      "Create missing name", 
      "City.gif", _function);
  }
}
