/*
 * generated by Xtext
 */
package politicianBiDsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PBiDslUiModule extends politicianBiDsl.ui.AbstractPBiDslUiModule {
	public PBiDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
