/*
* generated by Xtext
*/
package politicianBiDsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import politicianBiDsl.services.PBiDslGrammarAccess;

public class PBiDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PBiDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected politicianBiDsl.parser.antlr.internal.InternalPBiDslParser createParser(XtextTokenStream stream) {
		return new politicianBiDsl.parser.antlr.internal.InternalPBiDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "City";
	}
	
	public PBiDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PBiDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
