/*
 * generated by Xtext
 */
package politicianBiDsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PBiDslRuntimeModule extends politicianBiDsl.AbstractPBiDslRuntimeModule {

}
