/*
* generated by Xtext
*/
package politicianBiDsl.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class PBiDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class CityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "City");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cPartiesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cPartiesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cPartiesPartyParserRuleCall_3_2_0 = (RuleCall)cPartiesAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cPartiesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cPartiesPartyParserRuleCall_3_3_1_0 = (RuleCall)cPartiesAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cIndepsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cIndepsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cIndepsPoliticianParserRuleCall_6_0 = (RuleCall)cIndepsAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cIndepsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cIndepsPoliticianParserRuleCall_7_1_0 = (RuleCall)cIndepsAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//City:
		//	"City" name=STRING "{" ("parties" "{" parties+=Party ("," parties+=Party)* "}")? "indeps" "{" indeps+=Politician (","
		//	indeps+=Politician)* "}" "}";
		public ParserRule getRule() { return rule; }

		//"City" name=STRING "{" ("parties" "{" parties+=Party ("," parties+=Party)* "}")? "indeps" "{" indeps+=Politician (","
		//indeps+=Politician)* "}" "}"
		public Group getGroup() { return cGroup; }

		//"City"
		public Keyword getCityKeyword_0() { return cCityKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("parties" "{" parties+=Party ("," parties+=Party)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"parties"
		public Keyword getPartiesKeyword_3_0() { return cPartiesKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//parties+=Party
		public Assignment getPartiesAssignment_3_2() { return cPartiesAssignment_3_2; }

		//Party
		public RuleCall getPartiesPartyParserRuleCall_3_2_0() { return cPartiesPartyParserRuleCall_3_2_0; }

		//("," parties+=Party)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//parties+=Party
		public Assignment getPartiesAssignment_3_3_1() { return cPartiesAssignment_3_3_1; }

		//Party
		public RuleCall getPartiesPartyParserRuleCall_3_3_1_0() { return cPartiesPartyParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//"indeps"
		public Keyword getIndepsKeyword_4() { return cIndepsKeyword_4; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }

		//indeps+=Politician
		public Assignment getIndepsAssignment_6() { return cIndepsAssignment_6; }

		//Politician
		public RuleCall getIndepsPoliticianParserRuleCall_6_0() { return cIndepsPoliticianParserRuleCall_6_0; }

		//("," indeps+=Politician)*
		public Group getGroup_7() { return cGroup_7; }

		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }

		//indeps+=Politician
		public Assignment getIndepsAssignment_7_1() { return cIndepsAssignment_7_1; }

		//Politician
		public RuleCall getIndepsPoliticianParserRuleCall_7_1_0() { return cIndepsPoliticianParserRuleCall_7_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class PartyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Party");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPartyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cAcronymKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cAcronymAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAcronymSTRINGTerminalRuleCall_4_0 = (RuleCall)cAcronymAssignment_4.eContents().get(0);
		private final Keyword cPresidentKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPresidentAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cPresidentPoliticianCrossReference_6_0 = (CrossReference)cPresidentAssignment_6.eContents().get(0);
		private final RuleCall cPresidentPoliticianIDTerminalRuleCall_6_0_1 = (RuleCall)cPresidentPoliticianCrossReference_6_0.eContents().get(1);
		private final Keyword cPolsKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cLeftSquareBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cPolsAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cPolsPoliticianParserRuleCall_9_0 = (RuleCall)cPolsAssignment_9.eContents().get(0);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cCommaKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Assignment cPolsAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cPolsPoliticianParserRuleCall_10_1_0 = (RuleCall)cPolsAssignment_10_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//Party:
		//	"Party" name=STRING "{" "acronym" acronym=STRING "president" president=[Politician] "pols" "[" pols+=Politician (","
		//	pols+=Politician)* "]" "}";
		public ParserRule getRule() { return rule; }

		//"Party" name=STRING "{" "acronym" acronym=STRING "president" president=[Politician] "pols" "[" pols+=Politician (","
		//pols+=Politician)* "]" "}"
		public Group getGroup() { return cGroup; }

		//"Party"
		public Keyword getPartyKeyword_0() { return cPartyKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"acronym"
		public Keyword getAcronymKeyword_3() { return cAcronymKeyword_3; }

		//acronym=STRING
		public Assignment getAcronymAssignment_4() { return cAcronymAssignment_4; }

		//STRING
		public RuleCall getAcronymSTRINGTerminalRuleCall_4_0() { return cAcronymSTRINGTerminalRuleCall_4_0; }

		//"president"
		public Keyword getPresidentKeyword_5() { return cPresidentKeyword_5; }

		//president=[Politician]
		public Assignment getPresidentAssignment_6() { return cPresidentAssignment_6; }

		//[Politician]
		public CrossReference getPresidentPoliticianCrossReference_6_0() { return cPresidentPoliticianCrossReference_6_0; }

		//ID
		public RuleCall getPresidentPoliticianIDTerminalRuleCall_6_0_1() { return cPresidentPoliticianIDTerminalRuleCall_6_0_1; }

		//"pols"
		public Keyword getPolsKeyword_7() { return cPolsKeyword_7; }

		//"["
		public Keyword getLeftSquareBracketKeyword_8() { return cLeftSquareBracketKeyword_8; }

		//pols+=Politician
		public Assignment getPolsAssignment_9() { return cPolsAssignment_9; }

		//Politician
		public RuleCall getPolsPoliticianParserRuleCall_9_0() { return cPolsPoliticianParserRuleCall_9_0; }

		//("," pols+=Politician)*
		public Group getGroup_10() { return cGroup_10; }

		//","
		public Keyword getCommaKeyword_10_0() { return cCommaKeyword_10_0; }

		//pols+=Politician
		public Assignment getPolsAssignment_10_1() { return cPolsAssignment_10_1; }

		//Politician
		public RuleCall getPolsPoliticianParserRuleCall_10_1_0() { return cPolsPoliticianParserRuleCall_10_1_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_11() { return cRightSquareBracketKeyword_11; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}

	public class PoliticianElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Politician");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cPolitician_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPublicOfficeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Politician:
		//	Politician_Impl | PublicOffice;
		public ParserRule getRule() { return rule; }

		//Politician_Impl | PublicOffice
		public Alternatives getAlternatives() { return cAlternatives; }

		//Politician_Impl
		public RuleCall getPolitician_ImplParserRuleCall_0() { return cPolitician_ImplParserRuleCall_0; }

		//PublicOffice
		public RuleCall getPublicOfficeParserRuleCall_1() { return cPublicOfficeParserRuleCall_1; }
	}

	public class Politician_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Politician_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPoliticianKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cAgeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cAgeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAgeINTTerminalRuleCall_4_0 = (RuleCall)cAgeAssignment_4.eContents().get(0);
		private final Keyword cSexKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSexAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cSexSTRINGTerminalRuleCall_6_0 = (RuleCall)cSexAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Politician_Impl returns Politician:
		//	"Politician" name=STRING "{" "age" age=INT "sex" sex=STRING "}";
		public ParserRule getRule() { return rule; }

		//"Politician" name=STRING "{" "age" age=INT "sex" sex=STRING "}"
		public Group getGroup() { return cGroup; }

		//"Politician"
		public Keyword getPoliticianKeyword_0() { return cPoliticianKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"age"
		public Keyword getAgeKeyword_3() { return cAgeKeyword_3; }

		//age=INT
		public Assignment getAgeAssignment_4() { return cAgeAssignment_4; }

		//INT
		public RuleCall getAgeINTTerminalRuleCall_4_0() { return cAgeINTTerminalRuleCall_4_0; }

		//"sex"
		public Keyword getSexKeyword_5() { return cSexKeyword_5; }

		//sex=STRING
		public Assignment getSexAssignment_6() { return cSexAssignment_6; }

		//STRING
		public RuleCall getSexSTRINGTerminalRuleCall_6_0() { return cSexSTRINGTerminalRuleCall_6_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class PublicOfficeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PublicOffice");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPublicOfficeKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cAgeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cAgeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cAgeINTTerminalRuleCall_4_0 = (RuleCall)cAgeAssignment_4.eContents().get(0);
		private final Keyword cSexKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSexAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cSexSTRINGTerminalRuleCall_6_0 = (RuleCall)cSexAssignment_6.eContents().get(0);
		private final Keyword cInstNameKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cInstNameAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cInstNameSTRINGTerminalRuleCall_8_0 = (RuleCall)cInstNameAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//PublicOffice:
		//	"PublicOffice" name=STRING "{" "age" age=INT "sex" sex=STRING "instName" instName=STRING "}";
		public ParserRule getRule() { return rule; }

		//"PublicOffice" name=STRING "{" "age" age=INT "sex" sex=STRING "instName" instName=STRING "}"
		public Group getGroup() { return cGroup; }

		//"PublicOffice"
		public Keyword getPublicOfficeKeyword_0() { return cPublicOfficeKeyword_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"age"
		public Keyword getAgeKeyword_3() { return cAgeKeyword_3; }

		//age=INT
		public Assignment getAgeAssignment_4() { return cAgeAssignment_4; }

		//INT
		public RuleCall getAgeINTTerminalRuleCall_4_0() { return cAgeINTTerminalRuleCall_4_0; }

		//"sex"
		public Keyword getSexKeyword_5() { return cSexKeyword_5; }

		//sex=STRING
		public Assignment getSexAssignment_6() { return cSexAssignment_6; }

		//STRING
		public RuleCall getSexSTRINGTerminalRuleCall_6_0() { return cSexSTRINGTerminalRuleCall_6_0; }

		//"instName"
		public Keyword getInstNameKeyword_7() { return cInstNameKeyword_7; }

		//instName=STRING
		public Assignment getInstNameAssignment_8() { return cInstNameAssignment_8; }

		//STRING
		public RuleCall getInstNameSTRINGTerminalRuleCall_8_0() { return cInstNameSTRINGTerminalRuleCall_8_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	
	
	private CityElements pCity;
	private PartyElements pParty;
	private PoliticianElements pPolitician;
	private Politician_ImplElements pPolitician_Impl;
	private PublicOfficeElements pPublicOffice;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public PBiDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("politicianBiDsl.PBiDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//City:
	//	"City" name=STRING "{" ("parties" "{" parties+=Party ("," parties+=Party)* "}")? "indeps" "{" indeps+=Politician (","
	//	indeps+=Politician)* "}" "}";
	public CityElements getCityAccess() {
		return (pCity != null) ? pCity : (pCity = new CityElements());
	}
	
	public ParserRule getCityRule() {
		return getCityAccess().getRule();
	}

	//Party:
	//	"Party" name=STRING "{" "acronym" acronym=STRING "president" president=[Politician] "pols" "[" pols+=Politician (","
	//	pols+=Politician)* "]" "}";
	public PartyElements getPartyAccess() {
		return (pParty != null) ? pParty : (pParty = new PartyElements());
	}
	
	public ParserRule getPartyRule() {
		return getPartyAccess().getRule();
	}

	//Politician:
	//	Politician_Impl | PublicOffice;
	public PoliticianElements getPoliticianAccess() {
		return (pPolitician != null) ? pPolitician : (pPolitician = new PoliticianElements());
	}
	
	public ParserRule getPoliticianRule() {
		return getPoliticianAccess().getRule();
	}

	//Politician_Impl returns Politician:
	//	"Politician" name=STRING "{" "age" age=INT "sex" sex=STRING "}";
	public Politician_ImplElements getPolitician_ImplAccess() {
		return (pPolitician_Impl != null) ? pPolitician_Impl : (pPolitician_Impl = new Politician_ImplElements());
	}
	
	public ParserRule getPolitician_ImplRule() {
		return getPolitician_ImplAccess().getRule();
	}

	//PublicOffice:
	//	"PublicOffice" name=STRING "{" "age" age=INT "sex" sex=STRING "instName" instName=STRING "}";
	public PublicOfficeElements getPublicOfficeAccess() {
		return (pPublicOffice != null) ? pPublicOffice : (pPublicOffice = new PublicOfficeElements());
	}
	
	public ParserRule getPublicOfficeRule() {
		return getPublicOfficeAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
